# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/frederickampsup/Documents/clasp-new

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/frederickampsup/Documents/clasp-new

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frederickampsup/Documents/clasp-new/CMakeFiles /home/frederickampsup/Documents/clasp-new//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frederickampsup/Documents/clasp-new/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lexer_test

# Build rule for target.
lexer_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lexer_test
.PHONY : lexer_test

# fast build rule for target.
lexer_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/build
.PHONY : lexer_test/fast

#=============================================================================
# Target rules for targets named parser_test

# Build rule for target.
parser_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parser_test
.PHONY : parser_test

# fast build rule for target.
parser_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/build
.PHONY : parser_test/fast

#=============================================================================
# Target rules for targets named ss_test

# Build rule for target.
ss_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ss_test
.PHONY : ss_test

# fast build rule for target.
ss_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/build
.PHONY : ss_test/fast

src/ast.o: src/ast.c.o
.PHONY : src/ast.o

# target to build an object file
src/ast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/src/ast.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/src/ast.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/src/ast.c.o
.PHONY : src/ast.c.o

src/ast.i: src/ast.c.i
.PHONY : src/ast.i

# target to preprocess a source file
src/ast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/src/ast.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/src/ast.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/src/ast.c.i
.PHONY : src/ast.c.i

src/ast.s: src/ast.c.s
.PHONY : src/ast.s

# target to generate assembly for a file
src/ast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/src/ast.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/src/ast.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/src/ast.c.s
.PHONY : src/ast.c.s

src/lexer.o: src/lexer.c.o
.PHONY : src/lexer.o

# target to build an object file
src/lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/src/lexer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/src/lexer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/src/lexer.c.o
.PHONY : src/lexer.c.o

src/lexer.i: src/lexer.c.i
.PHONY : src/lexer.i

# target to preprocess a source file
src/lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/src/lexer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/src/lexer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/src/lexer.c.i
.PHONY : src/lexer.c.i

src/lexer.s: src/lexer.c.s
.PHONY : src/lexer.s

# target to generate assembly for a file
src/lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/src/lexer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/src/lexer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/src/lexer.c.s
.PHONY : src/lexer.c.s

src/parser.o: src/parser.c.o
.PHONY : src/parser.o

# target to build an object file
src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/src/parser.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/src/parser.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/src/parser.c.o
.PHONY : src/parser.c.o

src/parser.i: src/parser.c.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/src/parser.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/src/parser.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/src/parser.c.i
.PHONY : src/parser.c.i

src/parser.s: src/parser.c.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/src/parser.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/src/parser.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/src/parser.c.s
.PHONY : src/parser.c.s

src/stringstream.o: src/stringstream.c.o
.PHONY : src/stringstream.o

# target to build an object file
src/stringstream.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/src/stringstream.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/src/stringstream.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/src/stringstream.c.o
.PHONY : src/stringstream.c.o

src/stringstream.i: src/stringstream.c.i
.PHONY : src/stringstream.i

# target to preprocess a source file
src/stringstream.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/src/stringstream.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/src/stringstream.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/src/stringstream.c.i
.PHONY : src/stringstream.c.i

src/stringstream.s: src/stringstream.c.s
.PHONY : src/stringstream.s

# target to generate assembly for a file
src/stringstream.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/src/stringstream.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/src/stringstream.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/src/stringstream.c.s
.PHONY : src/stringstream.c.s

tests/lexer_test.o: tests/lexer_test.c.o
.PHONY : tests/lexer_test.o

# target to build an object file
tests/lexer_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/tests/lexer_test.c.o
.PHONY : tests/lexer_test.c.o

tests/lexer_test.i: tests/lexer_test.c.i
.PHONY : tests/lexer_test.i

# target to preprocess a source file
tests/lexer_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/tests/lexer_test.c.i
.PHONY : tests/lexer_test.c.i

tests/lexer_test.s: tests/lexer_test.c.s
.PHONY : tests/lexer_test.s

# target to generate assembly for a file
tests/lexer_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lexer_test.dir/build.make CMakeFiles/lexer_test.dir/tests/lexer_test.c.s
.PHONY : tests/lexer_test.c.s

tests/parser_test.o: tests/parser_test.c.o
.PHONY : tests/parser_test.o

# target to build an object file
tests/parser_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/tests/parser_test.c.o
.PHONY : tests/parser_test.c.o

tests/parser_test.i: tests/parser_test.c.i
.PHONY : tests/parser_test.i

# target to preprocess a source file
tests/parser_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/tests/parser_test.c.i
.PHONY : tests/parser_test.c.i

tests/parser_test.s: tests/parser_test.c.s
.PHONY : tests/parser_test.s

# target to generate assembly for a file
tests/parser_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser_test.dir/build.make CMakeFiles/parser_test.dir/tests/parser_test.c.s
.PHONY : tests/parser_test.c.s

tests/ss_test.o: tests/ss_test.c.o
.PHONY : tests/ss_test.o

# target to build an object file
tests/ss_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/tests/ss_test.c.o
.PHONY : tests/ss_test.c.o

tests/ss_test.i: tests/ss_test.c.i
.PHONY : tests/ss_test.i

# target to preprocess a source file
tests/ss_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/tests/ss_test.c.i
.PHONY : tests/ss_test.c.i

tests/ss_test.s: tests/ss_test.c.s
.PHONY : tests/ss_test.s

# target to generate assembly for a file
tests/ss_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ss_test.dir/build.make CMakeFiles/ss_test.dir/tests/ss_test.c.s
.PHONY : tests/ss_test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... lexer_test"
	@echo "... parser_test"
	@echo "... ss_test"
	@echo "... src/ast.o"
	@echo "... src/ast.i"
	@echo "... src/ast.s"
	@echo "... src/lexer.o"
	@echo "... src/lexer.i"
	@echo "... src/lexer.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/stringstream.o"
	@echo "... src/stringstream.i"
	@echo "... src/stringstream.s"
	@echo "... tests/lexer_test.o"
	@echo "... tests/lexer_test.i"
	@echo "... tests/lexer_test.s"
	@echo "... tests/parser_test.o"
	@echo "... tests/parser_test.i"
	@echo "... tests/parser_test.s"
	@echo "... tests/ss_test.o"
	@echo "... tests/ss_test.i"
	@echo "... tests/ss_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

